Fix add item return of string / Add and Subtract of Quantity
wenyngcar/izra-vape-shop-inventory pull request #13
Opened 2024-12-03 06:59 UTC by EmTampz

2024-12-03 07:02 UTC, EmTampz commented
@wenyngcar @MiguelCanedo @kramnev

2024-12-06 03:11 UTC, wenyngcar requested changes
No huge changes, request changes are for good practices and readability.

2024-12-06 03:11 UTC, wenyngcar commented on frontend/src/components/Add_subtractQuantity.tsx
> +};
For consistency, use function declaration, not arrow function declaration.

2024-12-06 03:11 UTC, wenyngcar commented on frontend/src/components/Add_subtractQuantity.tsx
> +};
Do the same from review above.

2024-12-06 03:11 UTC, wenyngcar commented on frontend/src/components/columns.tsx
> +import QuantityCell from './Add_subtractQuantity';
Move import to the top.

2024-12-06 03:11 UTC, wenyngcar commented on frontend/src/components/Add_subtractQuantity.tsx
rename the file to add-subtract-quantity.tsx

2024-12-06 03:51 UTC, closed without merging