Used express-validator to validate data in the backend.
wenyngcar/izra-vape-shop-inventory pull request #31
Opened 2024-12-09 13:27 UTC by MiguelCanedo

Validated the following POST routes:
- create-brand
- create-product
- create-variant

2024-12-10 00:57 UTC, wenyngcar requested changes
Use schema instead of specifying validation in functions.
You can refer to this page: https://express-validator.github.io/docs/guides/schema-validation

2024-12-10 00:57 UTC, wenyngcar commented on backend/src/middleware/api/router.js
> +    validator.body("expiration").notEmpty().escape(),   // No validator for checking if Date is in ISO format.
Use schema

2024-12-10 00:57 UTC, wenyngcar commented on backend/src/middleware/api/router.js
> +    validator.body("category").notEmpty().escape(),
Use schema

2024-12-12 18:21 UTC, MiguelCanedo commented
I have replaced the functions with the validation schemas.

I didn't place the schemas into a separate file as I don't think we'll be reusing it.

2024-12-13 15:56 UTC, wenyngcar approved these changes

2024-12-13 15:56 UTC, merged